version: 0.2
phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 008971637333.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t saiyed .
      - docker tag saiyed:latest 008971637333.dkr.ecr.ca-central-1.amazonaws.com/saiyed-repo:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 008971637333.dkr.ecr.ca-central-1.amazonaws.com/saiyed-repo:latest
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
